### ISSUE TITLE
Ft_strsplit.c should include warning for trigger

### ISSUE THREAD

**Issue by ingochris** [SuperSpyTX/libft#1]
Dear @SuperSpyTX,

2018 was going so well thanks to CBT until your code came appeared.
The following are owed:

1. match.c
2. nmatch.c

Sincerely,
@ingochris

**Comment by SuperSpyTX** [comment]
![image](https://user-images.githubusercontent.com/978263/35470494-56ace30a-02ff-11e8-8137-483498d10b50.png)
@ingochris
